/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AccessCodePlanningModelDescription } from './accessCodePlanningModelDescription';
import type { PlanningModel } from './planningModel';
import type { AccessCodePlanningModelValidTill } from './accessCodePlanningModelValidTill';

export interface AccessCodePlanningModel {
  description?: AccessCodePlanningModelDescription;
  entity: PlanningModel;
  id: number;
  secret: string;
  validTill?: AccessCodePlanningModelValidTill;
}
