/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AddressUpdateModel } from './addressUpdateModel';
import type { ActionUpdateModelEta } from './actionUpdateModelEta';
import type { ActionUpdateModelEtd } from './actionUpdateModelEtd';
import type { ActionUpdateModelIdentifier } from './actionUpdateModelIdentifier';
import type { ActionUpdateModelInstructions } from './actionUpdateModelInstructions';
import type { ActionUpdateModelPerson } from './actionUpdateModelPerson';
import type { ActionUpdateModelRequirements } from './actionUpdateModelRequirements';
import type { ActionUpdateModelStatus } from './actionUpdateModelStatus';

export interface ActionUpdateModel {
  address: AddressUpdateModel;
  eta?: ActionUpdateModelEta;
  etd?: ActionUpdateModelEtd;
  id: number;
  identifier?: ActionUpdateModelIdentifier;
  instructions?: ActionUpdateModelInstructions;
  person?: ActionUpdateModelPerson;
  requirements?: ActionUpdateModelRequirements;
  status?: ActionUpdateModelStatus;
}
