/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityCreateModelIdentifier } from './activityCreateModelIdentifier';
import type { PairStatusRequirementInput } from './pairStatusRequirementInput';
import type { ActivityCreateModelShipmentExpeditor } from './activityCreateModelShipmentExpeditor';
import type { ActivityCreateModelShipmentIdentifier } from './activityCreateModelShipmentIdentifier';

export interface ActivityCreateModel {
  action: unknown;
  identifier?: ActivityCreateModelIdentifier;
  requirements: PairStatusRequirementInput[];
  shipmentExpeditor?: ActivityCreateModelShipmentExpeditor;
  shipmentIdentifier?: ActivityCreateModelShipmentIdentifier;
  statusType: unknown;
}
