/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityModelConsignment } from './activityModelConsignment';
import type { ActivityModelIdentifier } from './activityModelIdentifier';
import type { PairStatusRequirement } from './pairStatusRequirement';
import type { ActivityModelStatusesItem } from './activityModelStatusesItem';

export interface ActivityModel {
  action: unknown;
  consignment?: ActivityModelConsignment;
  id: number;
  identifier?: ActivityModelIdentifier;
  requirements: PairStatusRequirement[];
  statusType: unknown;
  statuses: ActivityModelStatusesItem[];
}
