/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AddressModel } from './addressModel';
import type { ActionModelEta } from './actionModelEta';
import type { ActionModelEtd } from './actionModelEtd';
import type { ActionModelIdentifier } from './actionModelIdentifier';
import type { ActionModelInstructions } from './actionModelInstructions';
import type { ActionModelPerson } from './actionModelPerson';
import type { ActionModelRequirements } from './actionModelRequirements';
import type { ActionModelStatus } from './actionModelStatus';

export interface ActionModel {
  address: AddressModel;
  eta?: ActionModelEta;
  etd?: ActionModelEtd;
  id: number;
  identifier?: ActionModelIdentifier;
  instructions?: ActionModelInstructions;
  person?: ActionModelPerson;
  requirements?: ActionModelRequirements;
  status?: ActionModelStatus;
}
