/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { RawDate } from './rawDate';
import type { ActivityModelStatusesItemOneOfDeliveredEmballage } from './activityModelStatusesItemOneOfDeliveredEmballage';
import type { DimensionModel } from './dimensionModel';
import type { ActivityModelStatusesItemOneOfDocuments } from './activityModelStatusesItemOneOfDocuments';
import type { HandoverModel } from './handoverModel';
import type { ActivityModelStatusesItemOneOfLocation } from './activityModelStatusesItemOneOfLocation';
import type { ActivityModelStatusesItemOneOfMessage } from './activityModelStatusesItemOneOfMessage';
import type { ActivityModelStatusesItemOneOfPerson } from './activityModelStatusesItemOneOfPerson';
import type { ActivityModelStatusesItemOneOfPickedUpEmballage } from './activityModelStatusesItemOneOfPickedUpEmballage';
import type { ActivityModelStatusesItemOneOfPlanningData } from './activityModelStatusesItemOneOfPlanningData';
import type { ActivityModelStatusesItemOneOfProperties } from './activityModelStatusesItemOneOfProperties';

export type ActivityModelStatusesItemOneOf = {
  created: RawDate;
  deliveredEmballage?: ActivityModelStatusesItemOneOfDeliveredEmballage;
  dimensions: DimensionModel[];
  documents?: ActivityModelStatusesItemOneOfDocuments;
  handover: HandoverModel;
  id: number;
  identifier: string;
  location?: ActivityModelStatusesItemOneOfLocation;
  message?: ActivityModelStatusesItemOneOfMessage;
  person?: ActivityModelStatusesItemOneOfPerson;
  pickedUpEmballage?: ActivityModelStatusesItemOneOfPickedUpEmballage;
  planningData?: ActivityModelStatusesItemOneOfPlanningData;
  properties?: ActivityModelStatusesItemOneOfProperties;
  state: unknown;
  type: unknown;
};
