/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ShipmentCompanyModel } from './shipmentCompanyModel';
import type { ActorModelConsignment } from './actorModelConsignment';
import type { ActionModel } from './actionModel';
import type { ActorModelPrice } from './actorModelPrice';
import type { ActorModelProgresses } from './actorModelProgresses';

export interface ActorModel {
  company: ShipmentCompanyModel;
  consignment?: ActorModelConsignment;
  delivery: ActionModel;
  id: number;
  pickup: ActionModel;
  price?: ActorModelPrice;
  progresses?: ActorModelProgresses;
}
