/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ShipmentCompanyUpdateModel } from './shipmentCompanyUpdateModel';
import type { ActionUpdateModel } from './actionUpdateModel';
import type { ActorUpdateModelPrice } from './actorUpdateModelPrice';
import type { ActorUpdateModelProgresses } from './actorUpdateModelProgresses';

export interface ActorUpdateModel {
  company: ShipmentCompanyUpdateModel;
  delivery: ActionUpdateModel;
  id: number;
  pickup: ActionUpdateModel;
  price?: ActorUpdateModelPrice;
  progresses?: ActorUpdateModelProgresses;
}
