/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ShipmentCompanyCreateModel } from './shipmentCompanyCreateModel';
import type { ActionCreateModel } from './actionCreateModel';
import type { ActorCreateModelPrice } from './actorCreateModelPrice';
import type { ActorCreateModelProgresses } from './actorCreateModelProgresses';

export interface ActorCreateModel {
  company: ShipmentCompanyCreateModel;
  delivery: ActionCreateModel;
  pickup: ActionCreateModel;
  price?: ActorCreateModelPrice;
  progresses?: ActorCreateModelProgresses;
}
