/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AddressUpdateModelCity } from './addressUpdateModelCity';
import type { AddressUpdateModelCoordinates } from './addressUpdateModelCoordinates';
import type { AddressUpdateModelCountry } from './addressUpdateModelCountry';
import type { AddressUpdateModelCountryCode } from './addressUpdateModelCountryCode';
import type { AddressUpdateModelName } from './addressUpdateModelName';
import type { AddressUpdateModelNumber } from './addressUpdateModelNumber';
import type { AddressUpdateModelStreet } from './addressUpdateModelStreet';
import type { AddressUpdateModelZipcode } from './addressUpdateModelZipcode';

export interface AddressUpdateModel {
  city?: AddressUpdateModelCity;
  coordinates?: AddressUpdateModelCoordinates;
  country?: AddressUpdateModelCountry;
  countryCode?: AddressUpdateModelCountryCode;
  id: number;
  name?: AddressUpdateModelName;
  number?: AddressUpdateModelNumber;
  street?: AddressUpdateModelStreet;
  zipcode?: AddressUpdateModelZipcode;
}
