/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AddressModelCity } from './addressModelCity';
import type { AddressModelCoordinates } from './addressModelCoordinates';
import type { AddressModelCountry } from './addressModelCountry';
import type { AddressModelCountryCode } from './addressModelCountryCode';
import type { AddressModelName } from './addressModelName';
import type { AddressModelNumber } from './addressModelNumber';
import type { AddressModelStreet } from './addressModelStreet';
import type { AddressModelZipcode } from './addressModelZipcode';

export interface AddressModel {
  city?: AddressModelCity;
  coordinates?: AddressModelCoordinates;
  country?: AddressModelCountry;
  countryCode?: AddressModelCountryCode;
  id: number;
  name?: AddressModelName;
  number?: AddressModelNumber;
  street?: AddressModelStreet;
  zipcode?: AddressModelZipcode;
}
