/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AddressCreateModelCity } from './addressCreateModelCity';
import type { AddressCreateModelCoordinates } from './addressCreateModelCoordinates';
import type { AddressCreateModelCountry } from './addressCreateModelCountry';
import type { AddressCreateModelCountryCode } from './addressCreateModelCountryCode';
import type { AddressCreateModelName } from './addressCreateModelName';
import type { AddressCreateModelNumber } from './addressCreateModelNumber';
import type { AddressCreateModelStreet } from './addressCreateModelStreet';
import type { AddressCreateModelZipcode } from './addressCreateModelZipcode';

export interface AddressCreateModel {
  city?: AddressCreateModelCity;
  coordinates?: AddressCreateModelCoordinates;
  country?: AddressCreateModelCountry;
  countryCode?: AddressCreateModelCountryCode;
  name?: AddressCreateModelName;
  number?: AddressCreateModelNumber;
  street?: AddressCreateModelStreet;
  zipcode?: AddressCreateModelZipcode;
}
