/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentCreateModel } from './documentCreateModel';
import type { StatusCreate } from './statusCreate';

export interface BundledStatusesCreateModel {
  documents: DocumentCreateModel[];
  statusCreateModels: StatusCreate[];
}
