/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { BundledStatusCreateModelDeliveredEmballage } from './bundledStatusCreateModelDeliveredEmballage';
import type { DimensionCreateModel } from './dimensionCreateModel';
import type { BundledStatusCreateModelDocuments } from './bundledStatusCreateModelDocuments';
import type { HandoverCreateModel } from './handoverCreateModel';
import type { BundledStatusCreateModelLocation } from './bundledStatusCreateModelLocation';
import type { BundledStatusCreateModelMessage } from './bundledStatusCreateModelMessage';
import type { BundledStatusCreateModelPerson } from './bundledStatusCreateModelPerson';
import type { BundledStatusCreateModelPickedUpEmballage } from './bundledStatusCreateModelPickedUpEmballage';
import type { BundledStatusCreateModelPlanningData } from './bundledStatusCreateModelPlanningData';
import type { BundledStatusCreateModelProperties } from './bundledStatusCreateModelProperties';

export interface BundledStatusCreateModel {
  deliveredEmballage?: BundledStatusCreateModelDeliveredEmballage;
  dimensions: DimensionCreateModel[];
  documents?: BundledStatusCreateModelDocuments;
  handover: HandoverCreateModel;
  identifier: string;
  location?: BundledStatusCreateModelLocation;
  message?: BundledStatusCreateModelMessage;
  person?: BundledStatusCreateModelPerson;
  pickedUpEmballage?: BundledStatusCreateModelPickedUpEmballage;
  planningData?: BundledStatusCreateModelPlanningData;
  properties?: BundledStatusCreateModelProperties;
  state: unknown;
  type: unknown;
}
