/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { StatusIDCreateModel } from './statusIDCreateModel';
import type { DocumentCreateModel } from './documentCreateModel';

export interface BundledStatusesIDCreateModel {
  statusCreateModels: StatusIDCreateModel[];
  documents: DocumentCreateModel[];
}
