/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AddressModel } from './addressModel';
import type { Url } from './url';
import type { CargoledgerCompanyModelPerson } from './cargoledgerCompanyModelPerson';

export interface CargoledgerCompanyModel {
  address: AddressModel;
  cargoledger: Url;
  id: number;
  name: string;
  person?: CargoledgerCompanyModelPerson;
}
