/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { Password } from './password';
import type { NewPassword } from './newPassword';

export interface ChangeOwnPasswordModel {
  current: Password;
  password: NewPassword;
}
