/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ActorUpdateModel } from './actorUpdateModel';
import type { ContainerUpdateModel } from './containerUpdateModel';
import type { ConsignmentUpdateModelCustoms } from './consignmentUpdateModelCustoms';
import type { ConsignmentUpdateModelDocuments } from './consignmentUpdateModelDocuments';
import type { ConsignmentUpdateModelIncoterms } from './consignmentUpdateModelIncoterms';
import type { ConsignmentUpdateModelIndicators } from './consignmentUpdateModelIndicators';
import type { ShipmentCompanyUpdateModel } from './shipmentCompanyUpdateModel';
import type { ConsignmentUpdateModelReferences } from './consignmentUpdateModelReferences';

export interface ConsignmentUpdateModel {
  actors: ActorUpdateModel[];
  containers: ContainerUpdateModel[];
  customs?: ConsignmentUpdateModelCustoms;
  documents?: ConsignmentUpdateModelDocuments;
  id: number;
  incoterms?: ConsignmentUpdateModelIncoterms;
  indicators?: ConsignmentUpdateModelIndicators;
  name: string;
  receiver: ShipmentCompanyUpdateModel;
  references?: ConsignmentUpdateModelReferences;
  sender: ShipmentCompanyUpdateModel;
}
