/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ActorCreateModel } from './actorCreateModel';
import type { ContainerCreateModel } from './containerCreateModel';
import type { ConsignmentCreateModelCustoms } from './consignmentCreateModelCustoms';
import type { ConsignmentCreateModelDocuments } from './consignmentCreateModelDocuments';
import type { ConsignmentCreateModelIncoterms } from './consignmentCreateModelIncoterms';
import type { ConsignmentCreateModelIndicators } from './consignmentCreateModelIndicators';
import type { ShipmentCompanyCreateModel } from './shipmentCompanyCreateModel';
import type { ConsignmentCreateModelReferences } from './consignmentCreateModelReferences';

export interface ConsignmentCreateModel {
  actors: ActorCreateModel[];
  containers: ContainerCreateModel[];
  customs?: ConsignmentCreateModelCustoms;
  documents?: ConsignmentCreateModelDocuments;
  incoterms?: ConsignmentCreateModelIncoterms;
  indicators?: ConsignmentCreateModelIndicators;
  name: string;
  receiver: ShipmentCompanyCreateModel;
  references?: ConsignmentCreateModelReferences;
  sender: ShipmentCompanyCreateModel;
}
