/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ActorModel } from './actorModel';
import type { ContainerModel } from './containerModel';
import type { ConsignmentModelCustoms } from './consignmentModelCustoms';
import type { ConsignmentModelDocuments } from './consignmentModelDocuments';
import type { ConsignmentModelIncoterms } from './consignmentModelIncoterms';
import type { ConsignmentModelIndicators } from './consignmentModelIndicators';
import type { ShipmentCompanyModel } from './shipmentCompanyModel';
import type { ConsignmentModelReferences } from './consignmentModelReferences';
import type { ConsignmentModelShipment } from './consignmentModelShipment';

export interface ConsignmentModel {
  actors: ActorModel[];
  containers: ContainerModel[];
  customs?: ConsignmentModelCustoms;
  documents?: ConsignmentModelDocuments;
  id: number;
  incoterms?: ConsignmentModelIncoterms;
  indicators?: ConsignmentModelIndicators;
  name: string;
  receiver: ShipmentCompanyModel;
  references?: ConsignmentModelReferences;
  sender: ShipmentCompanyModel;
  shipment?: ConsignmentModelShipment;
}
