/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ContainerTypeModelOneOfSize } from './containerTypeModelOneOfSize';
import type { ContainerTypeModelOneOfType } from './containerTypeModelOneOfType';

export type ContainerTypeModelOneOf = {
  size?: ContainerTypeModelOneOfSize;
  type?: ContainerTypeModelOneOfType;
};
