/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ContainerCreateModelBarcode } from './containerCreateModelBarcode';
import type { ContainerCreateModelDimensions } from './containerCreateModelDimensions';
import type { ContainerCreateModelIdentifier } from './containerCreateModelIdentifier';
import type { PacketCreateModel } from './packetCreateModel';
import type { ContainerCreateModelProperties } from './containerCreateModelProperties';
import type { ContainerCreateModelQuantity } from './containerCreateModelQuantity';
import type { ContainerCreateModelType } from './containerCreateModelType';

export interface ContainerCreateModel {
  barcode?: ContainerCreateModelBarcode;
  dimensions?: ContainerCreateModelDimensions;
  identifier?: ContainerCreateModelIdentifier;
  packets: PacketCreateModel[];
  properties?: ContainerCreateModelProperties;
  quantity?: ContainerCreateModelQuantity;
  type?: ContainerCreateModelType;
}
