/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ContainerTypeCreateModelOneOfSize } from './containerTypeCreateModelOneOfSize';
import type { ContainerTypeCreateModelOneOfType } from './containerTypeCreateModelOneOfType';

export type ContainerTypeCreateModelOneOf = {
  size?: ContainerTypeCreateModelOneOfSize;
  type?: ContainerTypeCreateModelOneOfType;
};
