/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ContainerModelBarcode } from './containerModelBarcode';
import type { ContainerModelDimensions } from './containerModelDimensions';
import type { ContainerModelIdentifier } from './containerModelIdentifier';
import type { PacketModel } from './packetModel';
import type { ContainerModelProperties } from './containerModelProperties';
import type { ContainerModelQuantity } from './containerModelQuantity';
import type { ContainerModelType } from './containerModelType';

export interface ContainerModel {
  barcode?: ContainerModelBarcode;
  dimensions?: ContainerModelDimensions;
  id: number;
  identifier?: ContainerModelIdentifier;
  packets: PacketModel[];
  properties?: ContainerModelProperties;
  quantity?: ContainerModelQuantity;
  type?: ContainerModelType;
}
