/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ContainerUpdateModelBarcode } from './containerUpdateModelBarcode';
import type { ContainerUpdateModelDimensions } from './containerUpdateModelDimensions';
import type { ContainerUpdateModelIdentifier } from './containerUpdateModelIdentifier';
import type { PacketUpdateModel } from './packetUpdateModel';
import type { ContainerUpdateModelProperties } from './containerUpdateModelProperties';
import type { ContainerUpdateModelQuantity } from './containerUpdateModelQuantity';
import type { ContainerUpdateModelType } from './containerUpdateModelType';

export interface ContainerUpdateModel {
  barcode?: ContainerUpdateModelBarcode;
  dimensions?: ContainerUpdateModelDimensions;
  id: number;
  identifier?: ContainerUpdateModelIdentifier;
  packets: PacketUpdateModel[];
  properties?: ContainerUpdateModelProperties;
  quantity?: ContainerUpdateModelQuantity;
  type?: ContainerUpdateModelType;
}
