/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAccessCodePlanningModelDescription } from './createAccessCodePlanningModelDescription';
import type { CreateAccessCodePlanningModelValidTill } from './createAccessCodePlanningModelValidTill';

export interface CreateAccessCodePlanningModel {
  description?: CreateAccessCodePlanningModelDescription;
  entity: number;
  validTill?: CreateAccessCodePlanningModelValidTill;
}
