/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { Email } from './email';
import type { NewPassword } from './newPassword';

export interface CreateUserModel {
  authorities: unknown[];
  email: Email;
  locked: boolean;
  password: NewPassword;
}
