/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { DimensionCreateModelAttributeId } from './dimensionCreateModelAttributeId';
import type { DimensionCreateModelUnitCode } from './dimensionCreateModelUnitCode';

export interface DimensionCreateModel {
  attributeId?: DimensionCreateModelAttributeId;
  unitCode?: DimensionCreateModelUnitCode;
  value: string;
}
