/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { DimensionUpdateModelAttributeId } from './dimensionUpdateModelAttributeId';
import type { DimensionUpdateModelUnitCode } from './dimensionUpdateModelUnitCode';

export interface DimensionUpdateModel {
  attributeId?: DimensionUpdateModelAttributeId;
  id: number;
  unitCode?: DimensionUpdateModelUnitCode;
  value: string;
}
