/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { DimensionModelAttributeId } from './dimensionModelAttributeId';
import type { RawDate } from './rawDate';
import type { DimensionModelUnitCode } from './dimensionModelUnitCode';

export interface DimensionModel {
  attributeId?: DimensionModelAttributeId;
  created: RawDate;
  id: number;
  unitCode?: DimensionModelUnitCode;
  value: string;
}
