/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentCreateModelMeta } from './documentCreateModelMeta';

export interface DocumentCreateModel {
  base64: string;
  meta?: DocumentCreateModelMeta;
  mime: string;
  name: string;
  type: unknown;
}
