/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentModelMeta } from './documentModelMeta';

export interface DocumentModel {
  base64: string;
  id: number;
  meta?: DocumentModelMeta;
  mime: string;
  name: string;
  type: unknown;
}
