/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentUpdateModelMeta } from './documentUpdateModelMeta';

export interface DocumentUpdateModel {
  base64: string;
  id: number;
  meta?: DocumentUpdateModelMeta;
  mime: string;
  name: string;
  type: unknown;
}
