/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { HandoverModelArrival } from './handoverModelArrival';
import type { HandoverModelFinish } from './handoverModelFinish';
import type { HandoverModelStart } from './handoverModelStart';

export interface HandoverModel {
  arrival?: HandoverModelArrival;
  finish?: HandoverModelFinish;
  start?: HandoverModelStart;
}
