/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { HandoverCreateModelArrival } from './handoverCreateModelArrival';
import type { HandoverCreateModelFinish } from './handoverCreateModelFinish';
import type { HandoverCreateModelStart } from './handoverCreateModelStart';

export interface HandoverCreateModel {
  arrival?: HandoverCreateModelArrival;
  finish?: HandoverCreateModelFinish;
  start?: HandoverCreateModelStart;
}
