/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { HealthBackend } from './healthBackend';
import type { DatabaseHealth } from './databaseHealth';

export interface Health {
  backend?: HealthBackend;
  database: DatabaseHealth;
  host: string;
}
