/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ItemUpdateModelDescription } from './itemUpdateModelDescription';
import type { ItemUpdateModelHscode } from './itemUpdateModelHscode';
import type { ItemUpdateModelIdentifier } from './itemUpdateModelIdentifier';
import type { ItemUpdateModelProperties } from './itemUpdateModelProperties';
import type { ItemUpdateModelSize } from './itemUpdateModelSize';

export interface ItemUpdateModel {
  description?: ItemUpdateModelDescription;
  hscode?: ItemUpdateModelHscode;
  id: number;
  identifier?: ItemUpdateModelIdentifier;
  properties?: ItemUpdateModelProperties;
  size?: ItemUpdateModelSize;
}
