/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ItemCreateModelDescription } from './itemCreateModelDescription';
import type { ItemCreateModelHscode } from './itemCreateModelHscode';
import type { ItemCreateModelIdentifier } from './itemCreateModelIdentifier';
import type { ItemCreateModelProperties } from './itemCreateModelProperties';
import type { ItemCreateModelSize } from './itemCreateModelSize';

export interface ItemCreateModel {
  description?: ItemCreateModelDescription;
  hscode?: ItemCreateModelHscode;
  identifier?: ItemCreateModelIdentifier;
  properties?: ItemCreateModelProperties;
  size?: ItemCreateModelSize;
}
