/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { RawDate } from './rawDate';
import type { ListAccessCodeModelDescription } from './listAccessCodeModelDescription';
import type { ListAccessCodeModelValidTill } from './listAccessCodeModelValidTill';

export interface ListAccessCodeModel {
  created: RawDate;
  description?: ListAccessCodeModelDescription;
  id: number;
  secret: string;
  validTill?: ListAccessCodeModelValidTill;
}
