/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { Email } from './email';
import type { Password } from './password';

export interface LoginUserModel {
  email: Email;
  password: Password;
}
