/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { MessageModelConsignment } from './messageModelConsignment';
import type { RawDate } from './rawDate';
import type { MessageModelMessage } from './messageModelMessage';
import type { MessageModelPlanning } from './messageModelPlanning';
import type { MessageModelShipment } from './messageModelShipment';
import type { MessageModelUser } from './messageModelUser';

export interface MessageModel {
  consignment?: MessageModelConsignment;
  created: RawDate;
  id: number;
  message?: MessageModelMessage;
  planning?: MessageModelPlanning;
  shipment?: MessageModelShipment;
  type: unknown;
  user?: MessageModelUser;
}
