/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PacketCreateModelDescription } from './packetCreateModelDescription';
import type { PacketCreateModelDimensions } from './packetCreateModelDimensions';
import type { PacketCreateModelIdentifier } from './packetCreateModelIdentifier';
import type { ItemCreateModel } from './itemCreateModel';
import type { PacketCreateModelMonetary } from './packetCreateModelMonetary';
import type { PacketCreateModelQuantity } from './packetCreateModelQuantity';

export interface PacketCreateModel {
  description?: PacketCreateModelDescription;
  dimensions?: PacketCreateModelDimensions;
  identifier?: PacketCreateModelIdentifier;
  items: ItemCreateModel[];
  monetary?: PacketCreateModelMonetary;
  quantity?: PacketCreateModelQuantity;
}
