/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PackagingTypeModelAliases } from './packagingTypeModelAliases';

export interface PackagingTypeModel {
  aliases?: PackagingTypeModelAliases;
  id: number;
  order: number;
  packagingType: string;
  required: boolean;
}
