/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PacketModelDescription } from './packetModelDescription';
import type { PacketModelDimensions } from './packetModelDimensions';
import type { PacketModelIdentifier } from './packetModelIdentifier';
import type { ItemModel } from './itemModel';
import type { PacketModelMonetary } from './packetModelMonetary';
import type { PacketModelQuantity } from './packetModelQuantity';

export interface PacketModel {
  description?: PacketModelDescription;
  dimensions?: PacketModelDimensions;
  id: number;
  identifier?: PacketModelIdentifier;
  items: ItemModel[];
  monetary?: PacketModelMonetary;
  quantity?: PacketModelQuantity;
}
