/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PaginationPeriod } from './paginationPeriod';
import type { PaginationSearch } from './paginationSearch';
import type { PaginationSort } from './paginationSort';

export interface Pagination {
  itemsPerPage: number;
  page: number;
  period?: PaginationPeriod;
  search?: PaginationSearch;
  sort?: PaginationSort;
}
