/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PersonCreateModelOneOfEmail } from './personCreateModelOneOfEmail';
import type { PersonCreateModelOneOfName } from './personCreateModelOneOfName';
import type { PersonCreateModelOneOfPhone } from './personCreateModelOneOfPhone';

export type PersonCreateModelOneOf = {
  email?: PersonCreateModelOneOfEmail;
  name?: PersonCreateModelOneOfName;
  phone?: PersonCreateModelOneOfPhone;
};
