/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PersonUpdateModelOneOfEmail } from './personUpdateModelOneOfEmail';
import type { PersonUpdateModelOneOfName } from './personUpdateModelOneOfName';
import type { PersonUpdateModelOneOfPhone } from './personUpdateModelOneOfPhone';

export type PersonUpdateModelOneOf = {
  email?: PersonUpdateModelOneOfEmail;
  id: number;
  name?: PersonUpdateModelOneOfName;
  phone?: PersonUpdateModelOneOfPhone;
};
