/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PlanningModel } from './planningModel';

export interface PlanningPaginationResult {
  items: PlanningModel[];
  total: number;
}
