/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ConsignmentModel } from './consignmentModel';
import type { RawDate } from './rawDate';
import type { PlanningModelDescription } from './planningModelDescription';
import type { PlanningModelIdentifier } from './planningModelIdentifier';
import type { PlanningModelInstructions } from './planningModelInstructions';
import type { PlanningModelName } from './planningModelName';
import type { PlanningModelSharedAt } from './planningModelSharedAt';
import type { PlanningModelStartDate } from './planningModelStartDate';
import type { StopModel } from './stopModel';
import type { PlanningModelUpdated } from './planningModelUpdated';
import type { PlanningModelUser } from './planningModelUser';
import type { VehicleModel } from './vehicleModel';

export interface PlanningModel {
  consignments: ConsignmentModel[];
  created: RawDate;
  description?: PlanningModelDescription;
  finished: boolean;
  id: number;
  identifier?: PlanningModelIdentifier;
  instructions?: PlanningModelInstructions;
  name?: PlanningModelName;
  sharedAt?: PlanningModelSharedAt;
  startDate?: PlanningModelStartDate;
  stops: StopModel[];
  updated?: PlanningModelUpdated;
  user?: PlanningModelUser;
  vehicles: VehicleModel[];
}
