/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PlanningCreateModelDescription } from './planningCreateModelDescription';
import type { PlanningCreateModelIdentifier } from './planningCreateModelIdentifier';
import type { PlanningCreateModelInstructions } from './planningCreateModelInstructions';
import type { NotifyParty } from './notifyParty';
import type { PlanningCreateModelPublicIdentifier } from './planningCreateModelPublicIdentifier';
import type { PlanningCreateModelStartDate } from './planningCreateModelStartDate';
import type { StopCreateModel } from './stopCreateModel';
import type { PlanningCreateModelUser } from './planningCreateModelUser';
import type { VehicleCreateModel } from './vehicleCreateModel';

export interface PlanningCreateModel {
  description?: PlanningCreateModelDescription;
  identifier?: PlanningCreateModelIdentifier;
  instructions?: PlanningCreateModelInstructions;
  notifyParties: NotifyParty[];
  publicIdentifier?: PlanningCreateModelPublicIdentifier;
  startDate?: PlanningCreateModelStartDate;
  stops: StopCreateModel[];
  user?: PlanningCreateModelUser;
  vehicles?: VehicleCreateModel[];
}
