/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ReportModelEcmr } from './reportModelEcmr';
import type { ReportFinished } from './reportFinished';
import type { StatusPaginationResult } from './statusPaginationResult';

export interface ReportModel {
  ecmr?: ReportModelEcmr;
  emailCount: number;
  importedConversionsCount: number;
  planning: ReportFinished;
  shipment: ReportFinished;
  smsCount: number;
  statuses: StatusPaginationResult;
  users: number;
}
