/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAccessCodePlanningModel } from './createAccessCodePlanningModel';

export interface RestA1CreateAccessCodePlanningModel {
  a0: CreateAccessCodePlanningModel;
}
