/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { BundledStatusesCreateModel } from './bundledStatusesCreateModel';

export interface RestA1BundledStatusesCreateModel {
  a0: BundledStatusesCreateModel;
}
