/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AccessCodeNotificationCreate } from './accessCodeNotificationCreate';

export interface RestA2UUIDAccessCodeNotificationCreate {
  a0: string;
  a1: AccessCodeNotificationCreate;
}
