/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { LoginUserModel } from './loginUserModel';

export interface RestA1LoginUserModel {
  a0: LoginUserModel;
}
