/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { PlanningCreateModel } from './planningCreateModel';

export interface RestA2PlanningCreateModelBoolean {
  a0: PlanningCreateModel;
  a1: boolean;
}
