/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ShipmentCreateModel } from './shipmentCreateModel';

export interface RestA1ShipmentCreateModel {
  a0: ShipmentCreateModel;
}
