/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { BundledStatusesIDCreateModel } from './bundledStatusesIDCreateModel';

export interface RestA1BundledStatusesIDCreateModel {
  a0: BundledStatusesIDCreateModel;
}
