/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ShipmentModelOneOfAta } from './shipmentModelOneOfAta';
import type { ConsignmentModel } from './consignmentModel';
import type { RawDate } from './rawDate';
import type { DocumentModel } from './documentModel';
import type { ShipmentModelOneOfEta } from './shipmentModelOneOfEta';
import type { CargoledgerCompanyModel } from './cargoledgerCompanyModel';
import type { ShipmentModelOneOfUpdated } from './shipmentModelOneOfUpdated';

export type ShipmentModelOneOf = {
  actorId: string;
  ata?: ShipmentModelOneOfAta;
  consignments: ConsignmentModel[];
  created: RawDate;
  documents: DocumentModel[];
  eta?: ShipmentModelOneOfEta;
  expeditor: CargoledgerCompanyModel;
  finished: boolean;
  id: number;
  identifier: string;
  name: string;
  updated?: ShipmentModelOneOfUpdated;
};
