/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ShipmentPaginationResultItemsItemOneOfAta } from './shipmentPaginationResultItemsItemOneOfAta';
import type { ConsignmentModel } from './consignmentModel';
import type { RawDate } from './rawDate';
import type { DocumentModel } from './documentModel';
import type { ShipmentPaginationResultItemsItemOneOfEta } from './shipmentPaginationResultItemsItemOneOfEta';
import type { CargoledgerCompanyModel } from './cargoledgerCompanyModel';
import type { ShipmentPaginationResultItemsItemOneOfUpdated } from './shipmentPaginationResultItemsItemOneOfUpdated';

export type ShipmentPaginationResultItemsItemOneOf = {
  actorId: string;
  ata?: ShipmentPaginationResultItemsItemOneOfAta;
  consignments: ConsignmentModel[];
  created: RawDate;
  documents: DocumentModel[];
  eta?: ShipmentPaginationResultItemsItemOneOfEta;
  expeditor: CargoledgerCompanyModel;
  finished: boolean;
  id: number;
  identifier: string;
  name: string;
  updated?: ShipmentPaginationResultItemsItemOneOfUpdated;
};
