/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { AddressModel } from './addressModel';
import type { ShipmentCompanyModelCargoledger } from './shipmentCompanyModelCargoledger';
import type { ShipmentCompanyModelPerson } from './shipmentCompanyModelPerson';
import type { ShipmentCompanyModelShared } from './shipmentCompanyModelShared';

export interface ShipmentCompanyModel {
  actorId: string;
  address: AddressModel;
  cargoledger?: ShipmentCompanyModelCargoledger;
  id: number;
  name: string;
  person?: ShipmentCompanyModelPerson;
  shared?: ShipmentCompanyModelShared;
}
