/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ConsignmentCreateModel } from './consignmentCreateModel';
import type { DocumentCreateModel } from './documentCreateModel';

export interface ShipmentCreateModel {
  actorId: string;
  consignments: ConsignmentCreateModel[];
  documents: DocumentCreateModel[];
  expeditor: number;
  identifier: string;
  name: string;
}
