/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { StatusCreateModelOneOfDeliveredEmballage } from './statusCreateModelOneOfDeliveredEmballage';
import type { DimensionCreateModel } from './dimensionCreateModel';
import type { StatusCreateModelOneOfDocuments } from './statusCreateModelOneOfDocuments';
import type { HandoverCreateModel } from './handoverCreateModel';
import type { StatusCreateModelOneOfLocation } from './statusCreateModelOneOfLocation';
import type { StatusCreateModelOneOfMessage } from './statusCreateModelOneOfMessage';
import type { StatusCreateModelOneOfPerson } from './statusCreateModelOneOfPerson';
import type { StatusCreateModelOneOfPickedUpEmballage } from './statusCreateModelOneOfPickedUpEmballage';
import type { StatusCreateModelOneOfPlanningData } from './statusCreateModelOneOfPlanningData';
import type { StatusCreateModelOneOfProperties } from './statusCreateModelOneOfProperties';

export type StatusCreateModelOneOf = {
  deliveredEmballage?: StatusCreateModelOneOfDeliveredEmballage;
  dimensions: DimensionCreateModel[];
  documents?: StatusCreateModelOneOfDocuments;
  handover: HandoverCreateModel;
  identifier: string;
  location?: StatusCreateModelOneOfLocation;
  message?: StatusCreateModelOneOfMessage;
  person?: StatusCreateModelOneOfPerson;
  pickedUpEmballage?: StatusCreateModelOneOfPickedUpEmballage;
  planningData?: StatusCreateModelOneOfPlanningData;
  properties?: StatusCreateModelOneOfProperties;
  state: unknown;
  type: unknown;
};
