/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { StatusPaginationResultItemsItem } from './statusPaginationResultItemsItem';

export interface StatusPaginationResult {
  items: StatusPaginationResultItemsItem[];
  total: number;
}
