/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { StatusUpdateModelOneOfDeliveredEmballage } from './statusUpdateModelOneOfDeliveredEmballage';
import type { DimensionUpdateModel } from './dimensionUpdateModel';
import type { StatusUpdateModelOneOfDocuments } from './statusUpdateModelOneOfDocuments';
import type { HandoverCreateModel } from './handoverCreateModel';
import type { StatusUpdateModelOneOfLocation } from './statusUpdateModelOneOfLocation';
import type { StatusUpdateModelOneOfMessage } from './statusUpdateModelOneOfMessage';
import type { StatusUpdateModelOneOfPerson } from './statusUpdateModelOneOfPerson';
import type { StatusUpdateModelOneOfPickedUpEmballage } from './statusUpdateModelOneOfPickedUpEmballage';
import type { StatusUpdateModelOneOfPlanningData } from './statusUpdateModelOneOfPlanningData';
import type { StatusUpdateModelOneOfProperties } from './statusUpdateModelOneOfProperties';

export type StatusUpdateModelOneOf = {
  deliveredEmballage?: StatusUpdateModelOneOfDeliveredEmballage;
  dimensions: DimensionUpdateModel[];
  documents?: StatusUpdateModelOneOfDocuments;
  handover: HandoverCreateModel;
  id: number;
  identifier: string;
  location?: StatusUpdateModelOneOfLocation;
  message?: StatusUpdateModelOneOfMessage;
  person?: StatusUpdateModelOneOfPerson;
  pickedUpEmballage?: StatusUpdateModelOneOfPickedUpEmballage;
  planningData?: StatusUpdateModelOneOfPlanningData;
  properties?: StatusUpdateModelOneOfProperties;
  state: unknown;
  type: unknown;
};
