/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { RawDate } from './rawDate';
import type { StatusModelOneOfDeliveredEmballage } from './statusModelOneOfDeliveredEmballage';
import type { DimensionModel } from './dimensionModel';
import type { StatusModelOneOfDocuments } from './statusModelOneOfDocuments';
import type { HandoverModel } from './handoverModel';
import type { StatusModelOneOfLocation } from './statusModelOneOfLocation';
import type { StatusModelOneOfMessage } from './statusModelOneOfMessage';
import type { StatusModelOneOfPerson } from './statusModelOneOfPerson';
import type { StatusModelOneOfPickedUpEmballage } from './statusModelOneOfPickedUpEmballage';
import type { StatusModelOneOfPlanningData } from './statusModelOneOfPlanningData';
import type { StatusModelOneOfProperties } from './statusModelOneOfProperties';

export type StatusModelOneOf = {
  created: RawDate;
  deliveredEmballage?: StatusModelOneOfDeliveredEmballage;
  dimensions: DimensionModel[];
  documents?: StatusModelOneOfDocuments;
  handover: HandoverModel;
  id: number;
  identifier: string;
  location?: StatusModelOneOfLocation;
  message?: StatusModelOneOfMessage;
  person?: StatusModelOneOfPerson;
  pickedUpEmballage?: StatusModelOneOfPickedUpEmballage;
  planningData?: StatusModelOneOfPlanningData;
  properties?: StatusModelOneOfProperties;
  state: unknown;
  type: unknown;
};
