/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { RawDate } from './rawDate';
import type { StatusPaginationResultItemsItemOneOfDeliveredEmballage } from './statusPaginationResultItemsItemOneOfDeliveredEmballage';
import type { DimensionModel } from './dimensionModel';
import type { StatusPaginationResultItemsItemOneOfDocuments } from './statusPaginationResultItemsItemOneOfDocuments';
import type { HandoverModel } from './handoverModel';
import type { StatusPaginationResultItemsItemOneOfLocation } from './statusPaginationResultItemsItemOneOfLocation';
import type { StatusPaginationResultItemsItemOneOfMessage } from './statusPaginationResultItemsItemOneOfMessage';
import type { StatusPaginationResultItemsItemOneOfPerson } from './statusPaginationResultItemsItemOneOfPerson';
import type { StatusPaginationResultItemsItemOneOfPickedUpEmballage } from './statusPaginationResultItemsItemOneOfPickedUpEmballage';
import type { StatusPaginationResultItemsItemOneOfPlanningData } from './statusPaginationResultItemsItemOneOfPlanningData';
import type { StatusPaginationResultItemsItemOneOfProperties } from './statusPaginationResultItemsItemOneOfProperties';

export type StatusPaginationResultItemsItemOneOf = {
  created: RawDate;
  deliveredEmballage?: StatusPaginationResultItemsItemOneOfDeliveredEmballage;
  dimensions: DimensionModel[];
  documents?: StatusPaginationResultItemsItemOneOfDocuments;
  handover: HandoverModel;
  id: number;
  identifier: string;
  location?: StatusPaginationResultItemsItemOneOfLocation;
  message?: StatusPaginationResultItemsItemOneOfMessage;
  person?: StatusPaginationResultItemsItemOneOfPerson;
  pickedUpEmballage?: StatusPaginationResultItemsItemOneOfPickedUpEmballage;
  planningData?: StatusPaginationResultItemsItemOneOfPlanningData;
  properties?: StatusPaginationResultItemsItemOneOfProperties;
  state: unknown;
  type: unknown;
};
