/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { BundledStatusCreateModel } from './bundledStatusCreateModel';

export interface StatusIDCreateModel {
  consignment: string;
  expeditor: number;
  shipment: string;
  status: BundledStatusCreateModel;
}
