/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityModel } from './activityModel';
import type { AddressModel } from './addressModel';
import type { StopModelEta } from './stopModelEta';
import type { StopModelEtd } from './stopModelEtd';
import type { StopModelIdentifier } from './stopModelIdentifier';
import type { StopModelInstructions } from './stopModelInstructions';

export interface StopModel {
  activities: ActivityModel[];
  address: AddressModel;
  eta?: StopModelEta;
  etd?: StopModelEtd;
  id: number;
  identifier?: StopModelIdentifier;
  instructions?: StopModelInstructions;
}
