/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityCreateModel } from './activityCreateModel';
import type { AddressCreateModel } from './addressCreateModel';
import type { StopCreateModelEta } from './stopCreateModelEta';
import type { StopCreateModelEtd } from './stopCreateModelEtd';
import type { StopCreateModelIdentifier } from './stopCreateModelIdentifier';
import type { StopCreateModelInstructions } from './stopCreateModelInstructions';

export interface StopCreateModel {
  activities: ActivityCreateModel[];
  address: AddressCreateModel;
  eta?: StopCreateModelEta;
  etd?: StopCreateModelEtd;
  identifier?: StopCreateModelIdentifier;
  instructions?: StopCreateModelInstructions;
}
