/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleModelDescription } from './vehicleModelDescription';
import type { VehicleModelLicensePlate } from './vehicleModelLicensePlate';

export interface VehicleModel {
  description?: VehicleModelDescription;
  id: number;
  licensePlate?: VehicleModelLicensePlate;
  type: unknown;
}
