/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * CleanArchitecture
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleCreateModelDescription } from './vehicleCreateModelDescription';
import type { VehicleCreateModelLicensePlate } from './vehicleCreateModelLicensePlate';

export interface VehicleCreateModel {
  description?: VehicleCreateModelDescription;
  licensePlate?: VehicleCreateModelLicensePlate;
  type: unknown;
}
