/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessCodeNotificationCreate
 */
export interface AccessCodeNotificationCreate {
    /**
     * 
     * @type {any}
     * @memberof AccessCodeNotificationCreate
     */
    medium: AccessCodeNotificationCreateMediumEnum;
    /**
     * 
     * @type {any}
     * @memberof AccessCodeNotificationCreate
     */
    message?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AccessCodeNotificationCreate
     */
    recipient: any | null;
}


/**
 * @export
 */
export const AccessCodeNotificationCreateMediumEnum = {
    Sms: 'SMS',
    Email: 'EMAIL',
    PushNotification: 'PUSH_NOTIFICATION'
} as const;
export type AccessCodeNotificationCreateMediumEnum = typeof AccessCodeNotificationCreateMediumEnum[keyof typeof AccessCodeNotificationCreateMediumEnum];


/**
 * Check if a given object implements the AccessCodeNotificationCreate interface.
 */
export function instanceOfAccessCodeNotificationCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "medium" in value;
    isInstance = isInstance && "recipient" in value;

    return isInstance;
}

export function AccessCodeNotificationCreateFromJSON(json: any): AccessCodeNotificationCreate {
    return AccessCodeNotificationCreateFromJSONTyped(json, false);
}

export function AccessCodeNotificationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessCodeNotificationCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medium': json['medium'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'recipient': json['recipient'],
    };
}

export function AccessCodeNotificationCreateToJSON(value?: AccessCodeNotificationCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'medium': value.medium,
        'message': value.message,
        'recipient': value.recipient,
    };
}

