/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressCreateModel } from './AddressCreateModel';
import {
    AddressCreateModelFromJSON,
    AddressCreateModelFromJSONTyped,
    AddressCreateModelToJSON,
} from './AddressCreateModel';

/**
 * 
 * @export
 * @interface ActionCreateModel
 */
export interface ActionCreateModel {
    /**
     * 
     * @type {AddressCreateModel}
     * @memberof ActionCreateModel
     */
    address: AddressCreateModel;
    /**
     * 
     * @type {any}
     * @memberof ActionCreateModel
     */
    eta?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionCreateModel
     */
    etd?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionCreateModel
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionCreateModel
     */
    instructions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionCreateModel
     */
    person?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionCreateModel
     */
    requirements?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionCreateModel
     */
    status?: any | null;
}

/**
 * Check if a given object implements the ActionCreateModel interface.
 */
export function instanceOfActionCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;

    return isInstance;
}

export function ActionCreateModelFromJSON(json: any): ActionCreateModel {
    return ActionCreateModelFromJSONTyped(json, false);
}

export function ActionCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': AddressCreateModelFromJSON(json['address']),
        'eta': !exists(json, 'eta') ? undefined : json['eta'],
        'etd': !exists(json, 'etd') ? undefined : json['etd'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
        'person': !exists(json, 'person') ? undefined : json['person'],
        'requirements': !exists(json, 'requirements') ? undefined : json['requirements'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ActionCreateModelToJSON(value?: ActionCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': AddressCreateModelToJSON(value.address),
        'eta': value.eta,
        'etd': value.etd,
        'identifier': value.identifier,
        'instructions': value.instructions,
        'person': value.person,
        'requirements': value.requirements,
        'status': value.status,
    };
}

