/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressUpdateModel } from './AddressUpdateModel';
import {
    AddressUpdateModelFromJSON,
    AddressUpdateModelFromJSONTyped,
    AddressUpdateModelToJSON,
} from './AddressUpdateModel';

/**
 * 
 * @export
 * @interface ActionUpdateModel
 */
export interface ActionUpdateModel {
    /**
     * 
     * @type {AddressUpdateModel}
     * @memberof ActionUpdateModel
     */
    address: AddressUpdateModel;
    /**
     * 
     * @type {any}
     * @memberof ActionUpdateModel
     */
    eta?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionUpdateModel
     */
    etd?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionUpdateModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionUpdateModel
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionUpdateModel
     */
    instructions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionUpdateModel
     */
    person?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionUpdateModel
     */
    requirements?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ActionUpdateModel
     */
    status?: any | null;
}

/**
 * Check if a given object implements the ActionUpdateModel interface.
 */
export function instanceOfActionUpdateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ActionUpdateModelFromJSON(json: any): ActionUpdateModel {
    return ActionUpdateModelFromJSONTyped(json, false);
}

export function ActionUpdateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionUpdateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': AddressUpdateModelFromJSON(json['address']),
        'eta': !exists(json, 'eta') ? undefined : json['eta'],
        'etd': !exists(json, 'etd') ? undefined : json['etd'],
        'id': json['id'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
        'person': !exists(json, 'person') ? undefined : json['person'],
        'requirements': !exists(json, 'requirements') ? undefined : json['requirements'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ActionUpdateModelToJSON(value?: ActionUpdateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': AddressUpdateModelToJSON(value.address),
        'eta': value.eta,
        'etd': value.etd,
        'id': value.id,
        'identifier': value.identifier,
        'instructions': value.instructions,
        'person': value.person,
        'requirements': value.requirements,
        'status': value.status,
    };
}

