/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressModel
 */
export interface AddressModel {
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    city?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    coordinates?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    country?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    countryCode?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    number?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    street?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddressModel
     */
    zipcode?: any | null;
}

/**
 * Check if a given object implements the AddressModel interface.
 */
export function instanceOfAddressModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function AddressModelFromJSON(json: any): AddressModel {
    return AddressModelFromJSONTyped(json, false);
}

export function AddressModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'city': !exists(json, 'city') ? undefined : json['city'],
        'coordinates': !exists(json, 'coordinates') ? undefined : json['coordinates'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'zipcode': !exists(json, 'zipcode') ? undefined : json['zipcode'],
    };
}

export function AddressModelToJSON(value?: AddressModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'city': value.city,
        'coordinates': value.coordinates,
        'country': value.country,
        'countryCode': value.countryCode,
        'id': value.id,
        'name': value.name,
        'number': value.number,
        'street': value.street,
        'zipcode': value.zipcode,
    };
}

