/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HandoverCreateModel } from './HandoverCreateModel';
import {
    HandoverCreateModelFromJSON,
    HandoverCreateModelFromJSONTyped,
    HandoverCreateModelToJSON,
} from './HandoverCreateModel';

/**
 * 
 * @export
 * @interface BundledStatusCreateModel
 */
export interface BundledStatusCreateModel {
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    deliveredEmballage?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    dimensions: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    documents?: any | null;
    /**
     * 
     * @type {HandoverCreateModel}
     * @memberof BundledStatusCreateModel
     */
    handover: HandoverCreateModel;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    identifier: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    location?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    message?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    person?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    pickedUpEmballage?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    planningData?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    properties?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    state: BundledStatusCreateModelStateEnum;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusCreateModel
     */
    type: BundledStatusCreateModelTypeEnum;
}


/**
 * @export
 */
export const BundledStatusCreateModelStateEnum = {
    Accepted: 'ACCEPTED',
    Declined: 'DECLINED',
    Damaged: 'DAMAGED',
    Manco: 'MANCO',
    NotReady: 'NOT_READY'
} as const;
export type BundledStatusCreateModelStateEnum = typeof BundledStatusCreateModelStateEnum[keyof typeof BundledStatusCreateModelStateEnum];

/**
 * @export
 */
export const BundledStatusCreateModelTypeEnum = {
    Pickup: 'PICKUP',
    Delivery: 'DELIVERY',
    CrossdockPickup: 'CROSSDOCK_PICKUP',
    CrossdockDelivery: 'CROSSDOCK_DELIVERY',
    PickupStarted: 'PICKUP_STARTED',
    DeliveryStarted: 'DELIVERY_STARTED',
    CrossdockPickupStarted: 'CROSSDOCK_PICKUP_STARTED',
    CrossdockDeliveryStarted: 'CROSSDOCK_DELIVERY_STARTED',
    OnRoute: 'ON_ROUTE'
} as const;
export type BundledStatusCreateModelTypeEnum = typeof BundledStatusCreateModelTypeEnum[keyof typeof BundledStatusCreateModelTypeEnum];


/**
 * Check if a given object implements the BundledStatusCreateModel interface.
 */
export function instanceOfBundledStatusCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dimensions" in value;
    isInstance = isInstance && "handover" in value;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function BundledStatusCreateModelFromJSON(json: any): BundledStatusCreateModel {
    return BundledStatusCreateModelFromJSONTyped(json, false);
}

export function BundledStatusCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundledStatusCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deliveredEmballage': !exists(json, 'deliveredEmballage') ? undefined : json['deliveredEmballage'],
        'dimensions': json['dimensions'],
        'documents': !exists(json, 'documents') ? undefined : json['documents'],
        'handover': HandoverCreateModelFromJSON(json['handover']),
        'identifier': json['identifier'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'person': !exists(json, 'person') ? undefined : json['person'],
        'pickedUpEmballage': !exists(json, 'pickedUpEmballage') ? undefined : json['pickedUpEmballage'],
        'planningData': !exists(json, 'planningData') ? undefined : json['planningData'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'state': json['state'],
        'type': json['type'],
    };
}

export function BundledStatusCreateModelToJSON(value?: BundledStatusCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deliveredEmballage': value.deliveredEmballage,
        'dimensions': value.dimensions,
        'documents': value.documents,
        'handover': HandoverCreateModelToJSON(value.handover),
        'identifier': value.identifier,
        'location': value.location,
        'message': value.message,
        'person': value.person,
        'pickedUpEmballage': value.pickedUpEmballage,
        'planningData': value.planningData,
        'properties': value.properties,
        'state': value.state,
        'type': value.type,
    };
}

