/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BundledStatusesCreateModel
 */
export interface BundledStatusesCreateModel {
    /**
     * 
     * @type {any}
     * @memberof BundledStatusesCreateModel
     */
    documents: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusesCreateModel
     */
    statusCreateModels: any | null;
}

/**
 * Check if a given object implements the BundledStatusesCreateModel interface.
 */
export function instanceOfBundledStatusesCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "documents" in value;
    isInstance = isInstance && "statusCreateModels" in value;

    return isInstance;
}

export function BundledStatusesCreateModelFromJSON(json: any): BundledStatusesCreateModel {
    return BundledStatusesCreateModelFromJSONTyped(json, false);
}

export function BundledStatusesCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundledStatusesCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documents': json['documents'],
        'statusCreateModels': json['statusCreateModels'],
    };
}

export function BundledStatusesCreateModelToJSON(value?: BundledStatusesCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documents': value.documents,
        'statusCreateModels': value.statusCreateModels,
    };
}

