/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BundledStatusesIDCreateModel
 */
export interface BundledStatusesIDCreateModel {
    /**
     * 
     * @type {any}
     * @memberof BundledStatusesIDCreateModel
     */
    statusCreateModels: any | null;
    /**
     * 
     * @type {any}
     * @memberof BundledStatusesIDCreateModel
     */
    documents: any | null;
}

/**
 * Check if a given object implements the BundledStatusesIDCreateModel interface.
 */
export function instanceOfBundledStatusesIDCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCreateModels" in value;
    isInstance = isInstance && "documents" in value;

    return isInstance;
}

export function BundledStatusesIDCreateModelFromJSON(json: any): BundledStatusesIDCreateModel {
    return BundledStatusesIDCreateModelFromJSONTyped(json, false);
}

export function BundledStatusesIDCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundledStatusesIDCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCreateModels': json['statusCreateModels'],
        'documents': json['documents'],
    };
}

export function BundledStatusesIDCreateModelToJSON(value?: BundledStatusesIDCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusCreateModels': value.statusCreateModels,
        'documents': value.documents,
    };
}

