/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressModel } from './AddressModel';
import {
    AddressModelFromJSON,
    AddressModelFromJSONTyped,
    AddressModelToJSON,
} from './AddressModel';
import type { URL } from './URL';
import {
    URLFromJSON,
    URLFromJSONTyped,
    URLToJSON,
} from './URL';

/**
 * 
 * @export
 * @interface CargoledgerCompanyModel
 */
export interface CargoledgerCompanyModel {
    /**
     * 
     * @type {AddressModel}
     * @memberof CargoledgerCompanyModel
     */
    address: AddressModel;
    /**
     * 
     * @type {URL}
     * @memberof CargoledgerCompanyModel
     */
    cargoledger: URL;
    /**
     * 
     * @type {any}
     * @memberof CargoledgerCompanyModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof CargoledgerCompanyModel
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof CargoledgerCompanyModel
     */
    person?: any | null;
}

/**
 * Check if a given object implements the CargoledgerCompanyModel interface.
 */
export function instanceOfCargoledgerCompanyModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "cargoledger" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CargoledgerCompanyModelFromJSON(json: any): CargoledgerCompanyModel {
    return CargoledgerCompanyModelFromJSONTyped(json, false);
}

export function CargoledgerCompanyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CargoledgerCompanyModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': AddressModelFromJSON(json['address']),
        'cargoledger': URLFromJSON(json['cargoledger']),
        'id': json['id'],
        'name': json['name'],
        'person': !exists(json, 'person') ? undefined : json['person'],
    };
}

export function CargoledgerCompanyModelToJSON(value?: CargoledgerCompanyModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': AddressModelToJSON(value.address),
        'cargoledger': URLToJSON(value.cargoledger),
        'id': value.id,
        'name': value.name,
        'person': value.person,
    };
}

