/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NewPassword } from './NewPassword';
import {
    NewPasswordFromJSON,
    NewPasswordFromJSONTyped,
    NewPasswordToJSON,
} from './NewPassword';
import type { Password } from './Password';
import {
    PasswordFromJSON,
    PasswordFromJSONTyped,
    PasswordToJSON,
} from './Password';

/**
 * 
 * @export
 * @interface ChangeOwnPasswordModel
 */
export interface ChangeOwnPasswordModel {
    /**
     * 
     * @type {Password}
     * @memberof ChangeOwnPasswordModel
     */
    current: Password;
    /**
     * 
     * @type {NewPassword}
     * @memberof ChangeOwnPasswordModel
     */
    password: NewPassword;
}

/**
 * Check if a given object implements the ChangeOwnPasswordModel interface.
 */
export function instanceOfChangeOwnPasswordModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "current" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function ChangeOwnPasswordModelFromJSON(json: any): ChangeOwnPasswordModel {
    return ChangeOwnPasswordModelFromJSONTyped(json, false);
}

export function ChangeOwnPasswordModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeOwnPasswordModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'current': PasswordFromJSON(json['current']),
        'password': NewPasswordFromJSON(json['password']),
    };
}

export function ChangeOwnPasswordModelToJSON(value?: ChangeOwnPasswordModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current': PasswordToJSON(value.current),
        'password': NewPasswordToJSON(value.password),
    };
}

