/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NewPassword } from './NewPassword';
import {
    NewPasswordFromJSON,
    NewPasswordFromJSONTyped,
    NewPasswordToJSON,
} from './NewPassword';

/**
 * 
 * @export
 * @interface ChangePasswordModel
 */
export interface ChangePasswordModel {
    /**
     * 
     * @type {any}
     * @memberof ChangePasswordModel
     */
    id: any | null;
    /**
     * 
     * @type {NewPassword}
     * @memberof ChangePasswordModel
     */
    password: NewPassword;
}

/**
 * Check if a given object implements the ChangePasswordModel interface.
 */
export function instanceOfChangePasswordModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function ChangePasswordModelFromJSON(json: any): ChangePasswordModel {
    return ChangePasswordModelFromJSONTyped(json, false);
}

export function ChangePasswordModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'password': NewPasswordFromJSON(json['password']),
    };
}

export function ChangePasswordModelToJSON(value?: ChangePasswordModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'password': NewPasswordToJSON(value.password),
    };
}

