/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ShipmentCompanyCreateModel } from './ShipmentCompanyCreateModel';
import {
    ShipmentCompanyCreateModelFromJSON,
    ShipmentCompanyCreateModelFromJSONTyped,
    ShipmentCompanyCreateModelToJSON,
} from './ShipmentCompanyCreateModel';

/**
 * 
 * @export
 * @interface ConsignmentCreateModel
 */
export interface ConsignmentCreateModel {
    /**
     * 
     * @type {any}
     * @memberof ConsignmentCreateModel
     */
    actors: any | null;
    /**
     * 
     * @type {any}
     * @memberof ConsignmentCreateModel
     */
    containers: any | null;
    /**
     * 
     * @type {any}
     * @memberof ConsignmentCreateModel
     */
    customs?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ConsignmentCreateModel
     */
    documents?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ConsignmentCreateModel
     */
    incoterms?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ConsignmentCreateModel
     */
    indicators?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ConsignmentCreateModel
     */
    name: any | null;
    /**
     * 
     * @type {ShipmentCompanyCreateModel}
     * @memberof ConsignmentCreateModel
     */
    receiver: ShipmentCompanyCreateModel;
    /**
     * 
     * @type {any}
     * @memberof ConsignmentCreateModel
     */
    references?: any | null;
    /**
     * 
     * @type {ShipmentCompanyCreateModel}
     * @memberof ConsignmentCreateModel
     */
    sender: ShipmentCompanyCreateModel;
}

/**
 * Check if a given object implements the ConsignmentCreateModel interface.
 */
export function instanceOfConsignmentCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "actors" in value;
    isInstance = isInstance && "containers" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "receiver" in value;
    isInstance = isInstance && "sender" in value;

    return isInstance;
}

export function ConsignmentCreateModelFromJSON(json: any): ConsignmentCreateModel {
    return ConsignmentCreateModelFromJSONTyped(json, false);
}

export function ConsignmentCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignmentCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actors': json['actors'],
        'containers': json['containers'],
        'customs': !exists(json, 'customs') ? undefined : json['customs'],
        'documents': !exists(json, 'documents') ? undefined : json['documents'],
        'incoterms': !exists(json, 'incoterms') ? undefined : json['incoterms'],
        'indicators': !exists(json, 'indicators') ? undefined : json['indicators'],
        'name': json['name'],
        'receiver': ShipmentCompanyCreateModelFromJSON(json['receiver']),
        'references': !exists(json, 'references') ? undefined : json['references'],
        'sender': ShipmentCompanyCreateModelFromJSON(json['sender']),
    };
}

export function ConsignmentCreateModelToJSON(value?: ConsignmentCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actors': value.actors,
        'containers': value.containers,
        'customs': value.customs,
        'documents': value.documents,
        'incoterms': value.incoterms,
        'indicators': value.indicators,
        'name': value.name,
        'receiver': ShipmentCompanyCreateModelToJSON(value.receiver),
        'references': value.references,
        'sender': ShipmentCompanyCreateModelToJSON(value.sender),
    };
}

