/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerCreateModel
 */
export interface ContainerCreateModel {
    /**
     * 
     * @type {any}
     * @memberof ContainerCreateModel
     */
    barcode?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ContainerCreateModel
     */
    dimensions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ContainerCreateModel
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ContainerCreateModel
     */
    packets: any | null;
    /**
     * 
     * @type {any}
     * @memberof ContainerCreateModel
     */
    properties?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ContainerCreateModel
     */
    quantity?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ContainerCreateModel
     */
    type?: any | null;
}

/**
 * Check if a given object implements the ContainerCreateModel interface.
 */
export function instanceOfContainerCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "packets" in value;

    return isInstance;
}

export function ContainerCreateModelFromJSON(json: any): ContainerCreateModel {
    return ContainerCreateModelFromJSONTyped(json, false);
}

export function ContainerCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'barcode': !exists(json, 'barcode') ? undefined : json['barcode'],
        'dimensions': !exists(json, 'dimensions') ? undefined : json['dimensions'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'packets': json['packets'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function ContainerCreateModelToJSON(value?: ContainerCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'barcode': value.barcode,
        'dimensions': value.dimensions,
        'identifier': value.identifier,
        'packets': value.packets,
        'properties': value.properties,
        'quantity': value.quantity,
        'type': value.type,
    };
}

