/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatabaseHealth
 */
export interface DatabaseHealth {
    /**
     * 
     * @type {any}
     * @memberof DatabaseHealth
     */
    connected: any | null;
    /**
     * 
     * @type {any}
     * @memberof DatabaseHealth
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof DatabaseHealth
     */
    version: any | null;
}

/**
 * Check if a given object implements the DatabaseHealth interface.
 */
export function instanceOfDatabaseHealth(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "connected" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "version" in value;

    return isInstance;
}

export function DatabaseHealthFromJSON(json: any): DatabaseHealth {
    return DatabaseHealthFromJSONTyped(json, false);
}

export function DatabaseHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatabaseHealth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connected': json['connected'],
        'type': json['type'],
        'version': json['version'],
    };
}

export function DatabaseHealthToJSON(value?: DatabaseHealth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connected': value.connected,
        'type': value.type,
        'version': value.version,
    };
}

