/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DimensionModel
 */
export interface DimensionModel {
    /**
     * 
     * @type {any}
     * @memberof DimensionModel
     */
    attributeId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DimensionModel
     */
    created: any | null;
    /**
     * 
     * @type {any}
     * @memberof DimensionModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof DimensionModel
     */
    unitCode?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DimensionModel
     */
    value: any | null;
}

/**
 * Check if a given object implements the DimensionModel interface.
 */
export function instanceOfDimensionModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function DimensionModelFromJSON(json: any): DimensionModel {
    return DimensionModelFromJSONTyped(json, false);
}

export function DimensionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DimensionModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributeId': !exists(json, 'attributeId') ? undefined : json['attributeId'],
        'created': json['created'],
        'id': json['id'],
        'unitCode': !exists(json, 'unitCode') ? undefined : json['unitCode'],
        'value': json['value'],
    };
}

export function DimensionModelToJSON(value?: DimensionModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributeId': value.attributeId,
        'created': value.created,
        'id': value.id,
        'unitCode': value.unitCode,
        'value': value.value,
    };
}

