/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DimensionCreateModel
 */
export interface DimensionCreateModel {
    /**
     * 
     * @type {any}
     * @memberof DimensionCreateModel
     */
    attributeId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DimensionCreateModel
     */
    unitCode?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DimensionCreateModel
     */
    value: any | null;
}

/**
 * Check if a given object implements the DimensionCreateModel interface.
 */
export function instanceOfDimensionCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function DimensionCreateModelFromJSON(json: any): DimensionCreateModel {
    return DimensionCreateModelFromJSONTyped(json, false);
}

export function DimensionCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DimensionCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributeId': !exists(json, 'attributeId') ? undefined : json['attributeId'],
        'unitCode': !exists(json, 'unitCode') ? undefined : json['unitCode'],
        'value': json['value'],
    };
}

export function DimensionCreateModelToJSON(value?: DimensionCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributeId': value.attributeId,
        'unitCode': value.unitCode,
        'value': value.value,
    };
}

