/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentUpdateModel
 */
export interface DocumentUpdateModel {
    /**
     * 
     * @type {any}
     * @memberof DocumentUpdateModel
     */
    base64: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentUpdateModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentUpdateModel
     */
    meta?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentUpdateModel
     */
    mime: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentUpdateModel
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentUpdateModel
     */
    type: DocumentUpdateModelTypeEnum;
}


/**
 * @export
 */
export const DocumentUpdateModelTypeEnum = {
    Image: 'IMAGE',
    Document: 'DOCUMENT',
    Signature: 'SIGNATURE',
    ECmr: 'eCMR',
    Vagd: 'VAGD'
} as const;
export type DocumentUpdateModelTypeEnum = typeof DocumentUpdateModelTypeEnum[keyof typeof DocumentUpdateModelTypeEnum];


/**
 * Check if a given object implements the DocumentUpdateModel interface.
 */
export function instanceOfDocumentUpdateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "base64" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "mime" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function DocumentUpdateModelFromJSON(json: any): DocumentUpdateModel {
    return DocumentUpdateModelFromJSONTyped(json, false);
}

export function DocumentUpdateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentUpdateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'base64': json['base64'],
        'id': json['id'],
        'meta': !exists(json, 'meta') ? undefined : json['meta'],
        'mime': json['mime'],
        'name': json['name'],
        'type': json['type'],
    };
}

export function DocumentUpdateModelToJSON(value?: DocumentUpdateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'base64': value.base64,
        'id': value.id,
        'meta': value.meta,
        'mime': value.mime,
        'name': value.name,
        'type': value.type,
    };
}

