/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentCreateModel
 */
export interface DocumentCreateModel {
    /**
     * 
     * @type {any}
     * @memberof DocumentCreateModel
     */
    base64: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCreateModel
     */
    meta?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCreateModel
     */
    mime: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCreateModel
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocumentCreateModel
     */
    type: DocumentCreateModelTypeEnum;
}


/**
 * @export
 */
export const DocumentCreateModelTypeEnum = {
    Image: 'IMAGE',
    Document: 'DOCUMENT',
    Signature: 'SIGNATURE',
    ECmr: 'eCMR',
    Vagd: 'VAGD'
} as const;
export type DocumentCreateModelTypeEnum = typeof DocumentCreateModelTypeEnum[keyof typeof DocumentCreateModelTypeEnum];


/**
 * Check if a given object implements the DocumentCreateModel interface.
 */
export function instanceOfDocumentCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "base64" in value;
    isInstance = isInstance && "mime" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function DocumentCreateModelFromJSON(json: any): DocumentCreateModel {
    return DocumentCreateModelFromJSONTyped(json, false);
}

export function DocumentCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'base64': json['base64'],
        'meta': !exists(json, 'meta') ? undefined : json['meta'],
        'mime': json['mime'],
        'name': json['name'],
        'type': json['type'],
    };
}

export function DocumentCreateModelToJSON(value?: DocumentCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'base64': value.base64,
        'meta': value.meta,
        'mime': value.mime,
        'name': value.name,
        'type': value.type,
    };
}

