/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListAccessCodeModel
 */
export interface ListAccessCodeModel {
    /**
     * 
     * @type {any}
     * @memberof ListAccessCodeModel
     */
    created: any | null;
    /**
     * 
     * @type {any}
     * @memberof ListAccessCodeModel
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ListAccessCodeModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof ListAccessCodeModel
     */
    secret: any | null;
    /**
     * 
     * @type {any}
     * @memberof ListAccessCodeModel
     */
    validTill?: any | null;
}

/**
 * Check if a given object implements the ListAccessCodeModel interface.
 */
export function instanceOfListAccessCodeModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "secret" in value;

    return isInstance;
}

export function ListAccessCodeModelFromJSON(json: any): ListAccessCodeModel {
    return ListAccessCodeModelFromJSONTyped(json, false);
}

export function ListAccessCodeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAccessCodeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created': json['created'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': json['id'],
        'secret': json['secret'],
        'validTill': !exists(json, 'validTill') ? undefined : json['validTill'],
    };
}

export function ListAccessCodeModelToJSON(value?: ListAccessCodeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created': value.created,
        'description': value.description,
        'id': value.id,
        'secret': value.secret,
        'validTill': value.validTill,
    };
}

