/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackagingTypeModel
 */
export interface PackagingTypeModel {
    /**
     * 
     * @type {any}
     * @memberof PackagingTypeModel
     */
    aliases?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PackagingTypeModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof PackagingTypeModel
     */
    order: any | null;
    /**
     * 
     * @type {any}
     * @memberof PackagingTypeModel
     */
    packagingType: any | null;
    /**
     * 
     * @type {any}
     * @memberof PackagingTypeModel
     */
    required: any | null;
}

/**
 * Check if a given object implements the PackagingTypeModel interface.
 */
export function instanceOfPackagingTypeModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "order" in value;
    isInstance = isInstance && "packagingType" in value;
    isInstance = isInstance && "required" in value;

    return isInstance;
}

export function PackagingTypeModelFromJSON(json: any): PackagingTypeModel {
    return PackagingTypeModelFromJSONTyped(json, false);
}

export function PackagingTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackagingTypeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aliases': !exists(json, 'aliases') ? undefined : json['aliases'],
        'id': json['id'],
        'order': json['order'],
        'packagingType': json['packagingType'],
        'required': json['required'],
    };
}

export function PackagingTypeModelToJSON(value?: PackagingTypeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aliases': value.aliases,
        'id': value.id,
        'order': value.order,
        'packagingType': value.packagingType,
        'required': value.required,
    };
}

