/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PacketUpdateModel
 */
export interface PacketUpdateModel {
    /**
     * 
     * @type {any}
     * @memberof PacketUpdateModel
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PacketUpdateModel
     */
    dimensions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PacketUpdateModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof PacketUpdateModel
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PacketUpdateModel
     */
    items: any | null;
    /**
     * 
     * @type {any}
     * @memberof PacketUpdateModel
     */
    monetary?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PacketUpdateModel
     */
    quantity?: any | null;
}

/**
 * Check if a given object implements the PacketUpdateModel interface.
 */
export function instanceOfPacketUpdateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function PacketUpdateModelFromJSON(json: any): PacketUpdateModel {
    return PacketUpdateModelFromJSONTyped(json, false);
}

export function PacketUpdateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PacketUpdateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'dimensions': !exists(json, 'dimensions') ? undefined : json['dimensions'],
        'id': json['id'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'items': json['items'],
        'monetary': !exists(json, 'monetary') ? undefined : json['monetary'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function PacketUpdateModelToJSON(value?: PacketUpdateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'dimensions': value.dimensions,
        'id': value.id,
        'identifier': value.identifier,
        'items': value.items,
        'monetary': value.monetary,
        'quantity': value.quantity,
    };
}

