/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PairStringString
 */
export interface PairStringString {
    /**
     * 
     * @type {any}
     * @memberof PairStringString
     */
    key: any | null;
    /**
     * 
     * @type {any}
     * @memberof PairStringString
     */
    value: any | null;
}

/**
 * Check if a given object implements the PairStringString interface.
 */
export function instanceOfPairStringString(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function PairStringStringFromJSON(json: any): PairStringString {
    return PairStringStringFromJSONTyped(json, false);
}

export function PairStringStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): PairStringString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function PairStringStringToJSON(value?: PairStringString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

