/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PairStatusRequirementInput
 */
export interface PairStatusRequirementInput {
    /**
     * 
     * @type {any}
     * @memberof PairStatusRequirementInput
     */
    key: PairStatusRequirementInputKeyEnum;
    /**
     * 
     * @type {any}
     * @memberof PairStatusRequirementInput
     */
    value: PairStatusRequirementInputValueEnum;
}


/**
 * @export
 */
export const PairStatusRequirementInputKeyEnum = {
    Arrival: 'ARRIVAL',
    Image: 'IMAGE',
    Document: 'DOCUMENT',
    Message: 'MESSAGE',
    Scan: 'SCAN',
    Signature: 'SIGNATURE',
    ModifyShelvesExtensions: 'MODIFY_SHELVES_EXTENSIONS',
    FinishPlanning: 'FINISH_PLANNING',
    ActivityStarted: 'ACTIVITY_STARTED',
    Temperature: 'TEMPERATURE',
    ManualAcceptCheck: 'MANUAL_ACCEPT_CHECK',
    SpecifyDeclinedState: 'SPECIFY_DECLINED_STATE',
    EmballageDelivered: 'EMBALLAGE_DELIVERED',
    EmballagePickedUp: 'EMBALLAGE_PICKED_UP',
    Emballage: 'EMBALLAGE'
} as const;
export type PairStatusRequirementInputKeyEnum = typeof PairStatusRequirementInputKeyEnum[keyof typeof PairStatusRequirementInputKeyEnum];

/**
 * @export
 */
export const PairStatusRequirementInputValueEnum = {
    Optional: 'OPTIONAL',
    Required: 'REQUIRED',
    RequiredIfNotAccepted: 'REQUIRED_IF_NOT_ACCEPTED',
    RequiredIfDamaged: 'REQUIRED_IF_DAMAGED'
} as const;
export type PairStatusRequirementInputValueEnum = typeof PairStatusRequirementInputValueEnum[keyof typeof PairStatusRequirementInputValueEnum];


/**
 * Check if a given object implements the PairStatusRequirementInput interface.
 */
export function instanceOfPairStatusRequirementInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function PairStatusRequirementInputFromJSON(json: any): PairStatusRequirementInput {
    return PairStatusRequirementInputFromJSONTyped(json, false);
}

export function PairStatusRequirementInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PairStatusRequirementInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function PairStatusRequirementInputToJSON(value?: PairStatusRequirementInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

