/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Password
 */
export interface Password {
    /**
     * 
     * @type {any}
     * @memberof Password
     */
    value: any | null;
}

/**
 * Check if a given object implements the Password interface.
 */
export function instanceOfPassword(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function PasswordFromJSON(json: any): Password {
    return PasswordFromJSONTyped(json, false);
}

export function PasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): Password {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function PasswordToJSON(value?: Password | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

