/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanningModel
 */
export interface PlanningModel {
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    consignments: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    created: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    finished: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    instructions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    sharedAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    startDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    stops: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    updated?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    user?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningModel
     */
    vehicles: any | null;
}

/**
 * Check if a given object implements the PlanningModel interface.
 */
export function instanceOfPlanningModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "consignments" in value;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "finished" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "stops" in value;
    isInstance = isInstance && "vehicles" in value;

    return isInstance;
}

export function PlanningModelFromJSON(json: any): PlanningModel {
    return PlanningModelFromJSONTyped(json, false);
}

export function PlanningModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanningModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'consignments': json['consignments'],
        'created': json['created'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'finished': json['finished'],
        'id': json['id'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'sharedAt': !exists(json, 'sharedAt') ? undefined : json['sharedAt'],
        'startDate': !exists(json, 'startDate') ? undefined : json['startDate'],
        'stops': json['stops'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'vehicles': json['vehicles'],
    };
}

export function PlanningModelToJSON(value?: PlanningModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'consignments': value.consignments,
        'created': value.created,
        'description': value.description,
        'finished': value.finished,
        'id': value.id,
        'identifier': value.identifier,
        'instructions': value.instructions,
        'name': value.name,
        'sharedAt': value.sharedAt,
        'startDate': value.startDate,
        'stops': value.stops,
        'updated': value.updated,
        'user': value.user,
        'vehicles': value.vehicles,
    };
}

