/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanningCreateModel
 */
export interface PlanningCreateModel {
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    instructions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    notifyParties: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    publicIdentifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    startDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    stops: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    user?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PlanningCreateModel
     */
    vehicles?: any | null;
}

/**
 * Check if a given object implements the PlanningCreateModel interface.
 */
export function instanceOfPlanningCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "notifyParties" in value;
    isInstance = isInstance && "stops" in value;

    return isInstance;
}

export function PlanningCreateModelFromJSON(json: any): PlanningCreateModel {
    return PlanningCreateModelFromJSONTyped(json, false);
}

export function PlanningCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanningCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
        'notifyParties': json['notifyParties'],
        'publicIdentifier': !exists(json, 'publicIdentifier') ? undefined : json['publicIdentifier'],
        'startDate': !exists(json, 'startDate') ? undefined : json['startDate'],
        'stops': json['stops'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'vehicles': !exists(json, 'vehicles') ? undefined : json['vehicles'],
    };
}

export function PlanningCreateModelToJSON(value?: PlanningCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'identifier': value.identifier,
        'instructions': value.instructions,
        'notifyParties': value.notifyParties,
        'publicIdentifier': value.publicIdentifier,
        'startDate': value.startDate,
        'stops': value.stops,
        'user': value.user,
        'vehicles': value.vehicles,
    };
}

