/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProgressCreateModel
 */
export interface ProgressCreateModel {
    /**
     * 
     * @type {any}
     * @memberof ProgressCreateModel
     */
    status: any | null;
}

/**
 * Check if a given object implements the ProgressCreateModel interface.
 */
export function instanceOfProgressCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ProgressCreateModelFromJSON(json: any): ProgressCreateModel {
    return ProgressCreateModelFromJSONTyped(json, false);
}

export function ProgressCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgressCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function ProgressCreateModelToJSON(value?: ProgressCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

