/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportFinished
 */
export interface ReportFinished {
    /**
     * 
     * @type {any}
     * @memberof ReportFinished
     */
    finished: any | null;
    /**
     * 
     * @type {any}
     * @memberof ReportFinished
     */
    unfinished: any | null;
}

/**
 * Check if a given object implements the ReportFinished interface.
 */
export function instanceOfReportFinished(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "finished" in value;
    isInstance = isInstance && "unfinished" in value;

    return isInstance;
}

export function ReportFinishedFromJSON(json: any): ReportFinished {
    return ReportFinishedFromJSONTyped(json, false);
}

export function ReportFinishedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportFinished {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'finished': json['finished'],
        'unfinished': json['unfinished'],
    };
}

export function ReportFinishedToJSON(value?: ReportFinished | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'finished': value.finished,
        'unfinished': value.unfinished,
    };
}

