/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BundledStatusesCreateModel } from './BundledStatusesCreateModel';
import {
    BundledStatusesCreateModelFromJSON,
    BundledStatusesCreateModelFromJSONTyped,
    BundledStatusesCreateModelToJSON,
} from './BundledStatusesCreateModel';

/**
 * 
 * @export
 * @interface RestA1BundledStatusesCreateModel
 */
export interface RestA1BundledStatusesCreateModel {
    /**
     * 
     * @type {BundledStatusesCreateModel}
     * @memberof RestA1BundledStatusesCreateModel
     */
    a0: BundledStatusesCreateModel;
}

/**
 * Check if a given object implements the RestA1BundledStatusesCreateModel interface.
 */
export function instanceOfRestA1BundledStatusesCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1BundledStatusesCreateModelFromJSON(json: any): RestA1BundledStatusesCreateModel {
    return RestA1BundledStatusesCreateModelFromJSONTyped(json, false);
}

export function RestA1BundledStatusesCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1BundledStatusesCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': BundledStatusesCreateModelFromJSON(json['a0']),
    };
}

export function RestA1BundledStatusesCreateModelToJSON(value?: RestA1BundledStatusesCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': BundledStatusesCreateModelToJSON(value.a0),
    };
}

