/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';

/**
 * 
 * @export
 * @interface RestA1Pagination
 */
export interface RestA1Pagination {
    /**
     * 
     * @type {Pagination}
     * @memberof RestA1Pagination
     */
    a0: Pagination;
}

/**
 * Check if a given object implements the RestA1Pagination interface.
 */
export function instanceOfRestA1Pagination(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1PaginationFromJSON(json: any): RestA1Pagination {
    return RestA1PaginationFromJSONTyped(json, false);
}

export function RestA1PaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1Pagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': PaginationFromJSON(json['a0']),
    };
}

export function RestA1PaginationToJSON(value?: RestA1Pagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': PaginationToJSON(value.a0),
    };
}

