/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestA1Int
 */
export interface RestA1Int {
    /**
     * 
     * @type {any}
     * @memberof RestA1Int
     */
    a0: any | null;
}

/**
 * Check if a given object implements the RestA1Int interface.
 */
export function instanceOfRestA1Int(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1IntFromJSON(json: any): RestA1Int {
    return RestA1IntFromJSONTyped(json, false);
}

export function RestA1IntFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1Int {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': json['a0'],
    };
}

export function RestA1IntToJSON(value?: RestA1Int | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': value.a0,
    };
}

