/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChangePasswordModel } from './ChangePasswordModel';
import {
    ChangePasswordModelFromJSON,
    ChangePasswordModelFromJSONTyped,
    ChangePasswordModelToJSON,
} from './ChangePasswordModel';

/**
 * 
 * @export
 * @interface RestA1ChangePasswordModel
 */
export interface RestA1ChangePasswordModel {
    /**
     * 
     * @type {ChangePasswordModel}
     * @memberof RestA1ChangePasswordModel
     */
    a0: ChangePasswordModel;
}

/**
 * Check if a given object implements the RestA1ChangePasswordModel interface.
 */
export function instanceOfRestA1ChangePasswordModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1ChangePasswordModelFromJSON(json: any): RestA1ChangePasswordModel {
    return RestA1ChangePasswordModelFromJSONTyped(json, false);
}

export function RestA1ChangePasswordModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1ChangePasswordModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': ChangePasswordModelFromJSON(json['a0']),
    };
}

export function RestA1ChangePasswordModelToJSON(value?: RestA1ChangePasswordModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': ChangePasswordModelToJSON(value.a0),
    };
}

