/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ShipmentCreateModel } from './ShipmentCreateModel';
import {
    ShipmentCreateModelFromJSON,
    ShipmentCreateModelFromJSONTyped,
    ShipmentCreateModelToJSON,
} from './ShipmentCreateModel';

/**
 * 
 * @export
 * @interface RestA1ShipmentCreateModel
 */
export interface RestA1ShipmentCreateModel {
    /**
     * 
     * @type {ShipmentCreateModel}
     * @memberof RestA1ShipmentCreateModel
     */
    a0: ShipmentCreateModel;
}

/**
 * Check if a given object implements the RestA1ShipmentCreateModel interface.
 */
export function instanceOfRestA1ShipmentCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1ShipmentCreateModelFromJSON(json: any): RestA1ShipmentCreateModel {
    return RestA1ShipmentCreateModelFromJSONTyped(json, false);
}

export function RestA1ShipmentCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1ShipmentCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': ShipmentCreateModelFromJSON(json['a0']),
    };
}

export function RestA1ShipmentCreateModelToJSON(value?: RestA1ShipmentCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': ShipmentCreateModelToJSON(value.a0),
    };
}

