/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChangeOwnPasswordModel } from './ChangeOwnPasswordModel';
import {
    ChangeOwnPasswordModelFromJSON,
    ChangeOwnPasswordModelFromJSONTyped,
    ChangeOwnPasswordModelToJSON,
} from './ChangeOwnPasswordModel';

/**
 * 
 * @export
 * @interface RestA1ChangeOwnPasswordModel
 */
export interface RestA1ChangeOwnPasswordModel {
    /**
     * 
     * @type {ChangeOwnPasswordModel}
     * @memberof RestA1ChangeOwnPasswordModel
     */
    a0: ChangeOwnPasswordModel;
}

/**
 * Check if a given object implements the RestA1ChangeOwnPasswordModel interface.
 */
export function instanceOfRestA1ChangeOwnPasswordModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1ChangeOwnPasswordModelFromJSON(json: any): RestA1ChangeOwnPasswordModel {
    return RestA1ChangeOwnPasswordModelFromJSONTyped(json, false);
}

export function RestA1ChangeOwnPasswordModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1ChangeOwnPasswordModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': ChangeOwnPasswordModelFromJSON(json['a0']),
    };
}

export function RestA1ChangeOwnPasswordModelToJSON(value?: RestA1ChangeOwnPasswordModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': ChangeOwnPasswordModelToJSON(value.a0),
    };
}

