/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BundledStatusesIDCreateModel } from './BundledStatusesIDCreateModel';
import {
    BundledStatusesIDCreateModelFromJSON,
    BundledStatusesIDCreateModelFromJSONTyped,
    BundledStatusesIDCreateModelToJSON,
} from './BundledStatusesIDCreateModel';

/**
 * 
 * @export
 * @interface RestA1BundledStatusesIDCreateModel
 */
export interface RestA1BundledStatusesIDCreateModel {
    /**
     * 
     * @type {BundledStatusesIDCreateModel}
     * @memberof RestA1BundledStatusesIDCreateModel
     */
    a0: BundledStatusesIDCreateModel;
}

/**
 * Check if a given object implements the RestA1BundledStatusesIDCreateModel interface.
 */
export function instanceOfRestA1BundledStatusesIDCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1BundledStatusesIDCreateModelFromJSON(json: any): RestA1BundledStatusesIDCreateModel {
    return RestA1BundledStatusesIDCreateModelFromJSONTyped(json, false);
}

export function RestA1BundledStatusesIDCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1BundledStatusesIDCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': BundledStatusesIDCreateModelFromJSON(json['a0']),
    };
}

export function RestA1BundledStatusesIDCreateModelToJSON(value?: RestA1BundledStatusesIDCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': BundledStatusesIDCreateModelToJSON(value.a0),
    };
}

