/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateAccessCodePlanningModel } from './CreateAccessCodePlanningModel';
import {
    CreateAccessCodePlanningModelFromJSON,
    CreateAccessCodePlanningModelFromJSONTyped,
    CreateAccessCodePlanningModelToJSON,
} from './CreateAccessCodePlanningModel';

/**
 * 
 * @export
 * @interface RestA1CreateAccessCodePlanningModel
 */
export interface RestA1CreateAccessCodePlanningModel {
    /**
     * 
     * @type {CreateAccessCodePlanningModel}
     * @memberof RestA1CreateAccessCodePlanningModel
     */
    a0: CreateAccessCodePlanningModel;
}

/**
 * Check if a given object implements the RestA1CreateAccessCodePlanningModel interface.
 */
export function instanceOfRestA1CreateAccessCodePlanningModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1CreateAccessCodePlanningModelFromJSON(json: any): RestA1CreateAccessCodePlanningModel {
    return RestA1CreateAccessCodePlanningModelFromJSONTyped(json, false);
}

export function RestA1CreateAccessCodePlanningModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1CreateAccessCodePlanningModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': CreateAccessCodePlanningModelFromJSON(json['a0']),
    };
}

export function RestA1CreateAccessCodePlanningModelToJSON(value?: RestA1CreateAccessCodePlanningModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': CreateAccessCodePlanningModelToJSON(value.a0),
    };
}

