/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestA2IntString
 */
export interface RestA2IntString {
    /**
     * 
     * @type {any}
     * @memberof RestA2IntString
     */
    a0: any | null;
    /**
     * 
     * @type {any}
     * @memberof RestA2IntString
     */
    a1: any | null;
}

/**
 * Check if a given object implements the RestA2IntString interface.
 */
export function instanceOfRestA2IntString(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;
    isInstance = isInstance && "a1" in value;

    return isInstance;
}

export function RestA2IntStringFromJSON(json: any): RestA2IntString {
    return RestA2IntStringFromJSONTyped(json, false);
}

export function RestA2IntStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA2IntString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': json['a0'],
        'a1': json['a1'],
    };
}

export function RestA2IntStringToJSON(value?: RestA2IntString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': value.a0,
        'a1': value.a1,
    };
}

