/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';

/**
 * 
 * @export
 * @interface RestA1Email
 */
export interface RestA1Email {
    /**
     * 
     * @type {Email}
     * @memberof RestA1Email
     */
    a0: Email;
}

/**
 * Check if a given object implements the RestA1Email interface.
 */
export function instanceOfRestA1Email(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1EmailFromJSON(json: any): RestA1Email {
    return RestA1EmailFromJSONTyped(json, false);
}

export function RestA1EmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1Email {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': EmailFromJSON(json['a0']),
    };
}

export function RestA1EmailToJSON(value?: RestA1Email | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': EmailToJSON(value.a0),
    };
}

