/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccessCodeNotificationCreate } from './AccessCodeNotificationCreate';
import {
    AccessCodeNotificationCreateFromJSON,
    AccessCodeNotificationCreateFromJSONTyped,
    AccessCodeNotificationCreateToJSON,
} from './AccessCodeNotificationCreate';

/**
 * 
 * @export
 * @interface RestA2UUIDAccessCodeNotificationCreate
 */
export interface RestA2UUIDAccessCodeNotificationCreate {
    /**
     * 
     * @type {any}
     * @memberof RestA2UUIDAccessCodeNotificationCreate
     */
    a0: any | null;
    /**
     * 
     * @type {AccessCodeNotificationCreate}
     * @memberof RestA2UUIDAccessCodeNotificationCreate
     */
    a1: AccessCodeNotificationCreate;
}

/**
 * Check if a given object implements the RestA2UUIDAccessCodeNotificationCreate interface.
 */
export function instanceOfRestA2UUIDAccessCodeNotificationCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;
    isInstance = isInstance && "a1" in value;

    return isInstance;
}

export function RestA2UUIDAccessCodeNotificationCreateFromJSON(json: any): RestA2UUIDAccessCodeNotificationCreate {
    return RestA2UUIDAccessCodeNotificationCreateFromJSONTyped(json, false);
}

export function RestA2UUIDAccessCodeNotificationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA2UUIDAccessCodeNotificationCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': json['a0'],
        'a1': AccessCodeNotificationCreateFromJSON(json['a1']),
    };
}

export function RestA2UUIDAccessCodeNotificationCreateToJSON(value?: RestA2UUIDAccessCodeNotificationCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': value.a0,
        'a1': AccessCodeNotificationCreateToJSON(value.a1),
    };
}

