/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LoginUserModel } from './LoginUserModel';
import {
    LoginUserModelFromJSON,
    LoginUserModelFromJSONTyped,
    LoginUserModelToJSON,
} from './LoginUserModel';

/**
 * 
 * @export
 * @interface RestA1LoginUserModel
 */
export interface RestA1LoginUserModel {
    /**
     * 
     * @type {LoginUserModel}
     * @memberof RestA1LoginUserModel
     */
    a0: LoginUserModel;
}

/**
 * Check if a given object implements the RestA1LoginUserModel interface.
 */
export function instanceOfRestA1LoginUserModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1LoginUserModelFromJSON(json: any): RestA1LoginUserModel {
    return RestA1LoginUserModelFromJSONTyped(json, false);
}

export function RestA1LoginUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1LoginUserModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': LoginUserModelFromJSON(json['a0']),
    };
}

export function RestA1LoginUserModelToJSON(value?: RestA1LoginUserModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': LoginUserModelToJSON(value.a0),
    };
}

