/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';

/**
 * 
 * @export
 * @interface RestA2PaginationBoolean
 */
export interface RestA2PaginationBoolean {
    /**
     * 
     * @type {Pagination}
     * @memberof RestA2PaginationBoolean
     */
    a0: Pagination;
    /**
     * 
     * @type {any}
     * @memberof RestA2PaginationBoolean
     */
    a1: any | null;
}

/**
 * Check if a given object implements the RestA2PaginationBoolean interface.
 */
export function instanceOfRestA2PaginationBoolean(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;
    isInstance = isInstance && "a1" in value;

    return isInstance;
}

export function RestA2PaginationBooleanFromJSON(json: any): RestA2PaginationBoolean {
    return RestA2PaginationBooleanFromJSONTyped(json, false);
}

export function RestA2PaginationBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA2PaginationBoolean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': PaginationFromJSON(json['a0']),
        'a1': json['a1'],
    };
}

export function RestA2PaginationBooleanToJSON(value?: RestA2PaginationBoolean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': PaginationToJSON(value.a0),
        'a1': value.a1,
    };
}

