/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestA1String
 */
export interface RestA1String {
    /**
     * 
     * @type {any}
     * @memberof RestA1String
     */
    a0: any | null;
}

/**
 * Check if a given object implements the RestA1String interface.
 */
export function instanceOfRestA1String(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a0" in value;

    return isInstance;
}

export function RestA1StringFromJSON(json: any): RestA1String {
    return RestA1StringFromJSONTyped(json, false);
}

export function RestA1StringFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestA1String {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a0': json['a0'],
    };
}

export function RestA1StringToJSON(value?: RestA1String | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a0': value.a0,
    };
}

