/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressModel } from './AddressModel';
import {
    AddressModelFromJSON,
    AddressModelFromJSONTyped,
    AddressModelToJSON,
} from './AddressModel';

/**
 * 
 * @export
 * @interface ShipmentCompanyModel
 */
export interface ShipmentCompanyModel {
    /**
     * 
     * @type {any}
     * @memberof ShipmentCompanyModel
     */
    actorId: any | null;
    /**
     * 
     * @type {AddressModel}
     * @memberof ShipmentCompanyModel
     */
    address: AddressModel;
    /**
     * 
     * @type {any}
     * @memberof ShipmentCompanyModel
     */
    cargoledger?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ShipmentCompanyModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof ShipmentCompanyModel
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof ShipmentCompanyModel
     */
    person?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ShipmentCompanyModel
     */
    shared?: any | null;
}

/**
 * Check if a given object implements the ShipmentCompanyModel interface.
 */
export function instanceOfShipmentCompanyModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "actorId" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ShipmentCompanyModelFromJSON(json: any): ShipmentCompanyModel {
    return ShipmentCompanyModelFromJSONTyped(json, false);
}

export function ShipmentCompanyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentCompanyModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actorId': json['actorId'],
        'address': AddressModelFromJSON(json['address']),
        'cargoledger': !exists(json, 'cargoledger') ? undefined : json['cargoledger'],
        'id': json['id'],
        'name': json['name'],
        'person': !exists(json, 'person') ? undefined : json['person'],
        'shared': !exists(json, 'shared') ? undefined : json['shared'],
    };
}

export function ShipmentCompanyModelToJSON(value?: ShipmentCompanyModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actorId': value.actorId,
        'address': AddressModelToJSON(value.address),
        'cargoledger': value.cargoledger,
        'id': value.id,
        'name': value.name,
        'person': value.person,
        'shared': value.shared,
    };
}

