/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipmentPaginationResult
 */
export interface ShipmentPaginationResult {
    /**
     * 
     * @type {any}
     * @memberof ShipmentPaginationResult
     */
    items: any | null;
    /**
     * 
     * @type {any}
     * @memberof ShipmentPaginationResult
     */
    total: any | null;
}

/**
 * Check if a given object implements the ShipmentPaginationResult interface.
 */
export function instanceOfShipmentPaginationResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function ShipmentPaginationResultFromJSON(json: any): ShipmentPaginationResult {
    return ShipmentPaginationResultFromJSONTyped(json, false);
}

export function ShipmentPaginationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentPaginationResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': json['items'],
        'total': json['total'],
    };
}

export function ShipmentPaginationResultToJSON(value?: ShipmentPaginationResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items,
        'total': value.total,
    };
}

