/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BundledStatusCreateModel } from './BundledStatusCreateModel';
import {
    BundledStatusCreateModelFromJSON,
    BundledStatusCreateModelFromJSONTyped,
    BundledStatusCreateModelToJSON,
} from './BundledStatusCreateModel';

/**
 * 
 * @export
 * @interface StatusCreate
 */
export interface StatusCreate {
    /**
     * 
     * @type {BundledStatusCreateModel}
     * @memberof StatusCreate
     */
    status: BundledStatusCreateModel;
}

/**
 * Check if a given object implements the StatusCreate interface.
 */
export function instanceOfStatusCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function StatusCreateFromJSON(json: any): StatusCreate {
    return StatusCreateFromJSONTyped(json, false);
}

export function StatusCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': BundledStatusCreateModelFromJSON(json['status']),
    };
}

export function StatusCreateToJSON(value?: StatusCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': BundledStatusCreateModelToJSON(value.status),
    };
}

