/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressModel } from './AddressModel';
import {
    AddressModelFromJSON,
    AddressModelFromJSONTyped,
    AddressModelToJSON,
} from './AddressModel';

/**
 * 
 * @export
 * @interface StopModel
 */
export interface StopModel {
    /**
     * 
     * @type {any}
     * @memberof StopModel
     */
    activities: any | null;
    /**
     * 
     * @type {AddressModel}
     * @memberof StopModel
     */
    address: AddressModel;
    /**
     * 
     * @type {any}
     * @memberof StopModel
     */
    eta?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StopModel
     */
    etd?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StopModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof StopModel
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StopModel
     */
    instructions?: any | null;
}

/**
 * Check if a given object implements the StopModel interface.
 */
export function instanceOfStopModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "activities" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function StopModelFromJSON(json: any): StopModel {
    return StopModelFromJSONTyped(json, false);
}

export function StopModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activities': json['activities'],
        'address': AddressModelFromJSON(json['address']),
        'eta': !exists(json, 'eta') ? undefined : json['eta'],
        'etd': !exists(json, 'etd') ? undefined : json['etd'],
        'id': json['id'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
    };
}

export function StopModelToJSON(value?: StopModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activities': value.activities,
        'address': AddressModelToJSON(value.address),
        'eta': value.eta,
        'etd': value.etd,
        'id': value.id,
        'identifier': value.identifier,
        'instructions': value.instructions,
    };
}

