/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressCreateModel } from './AddressCreateModel';
import {
    AddressCreateModelFromJSON,
    AddressCreateModelFromJSONTyped,
    AddressCreateModelToJSON,
} from './AddressCreateModel';

/**
 * 
 * @export
 * @interface StopCreateModel
 */
export interface StopCreateModel {
    /**
     * 
     * @type {any}
     * @memberof StopCreateModel
     */
    activities: any | null;
    /**
     * 
     * @type {AddressCreateModel}
     * @memberof StopCreateModel
     */
    address: AddressCreateModel;
    /**
     * 
     * @type {any}
     * @memberof StopCreateModel
     */
    eta?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StopCreateModel
     */
    etd?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StopCreateModel
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StopCreateModel
     */
    instructions?: any | null;
}

/**
 * Check if a given object implements the StopCreateModel interface.
 */
export function instanceOfStopCreateModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "activities" in value;
    isInstance = isInstance && "address" in value;

    return isInstance;
}

export function StopCreateModelFromJSON(json: any): StopCreateModel {
    return StopCreateModelFromJSONTyped(json, false);
}

export function StopCreateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopCreateModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activities': json['activities'],
        'address': AddressCreateModelFromJSON(json['address']),
        'eta': !exists(json, 'eta') ? undefined : json['eta'],
        'etd': !exists(json, 'etd') ? undefined : json['etd'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
    };
}

export function StopCreateModelToJSON(value?: StopCreateModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activities': value.activities,
        'address': AddressCreateModelToJSON(value.address),
        'eta': value.eta,
        'etd': value.etd,
        'identifier': value.identifier,
        'instructions': value.instructions,
    };
}

