/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';

/**
 * 
 * @export
 * @interface UpdateUserModel
 */
export interface UpdateUserModel {
    /**
     * 
     * @type {any}
     * @memberof UpdateUserModel
     */
    authorities: any | null;
    /**
     * 
     * @type {Email}
     * @memberof UpdateUserModel
     */
    email: Email;
    /**
     * 
     * @type {any}
     * @memberof UpdateUserModel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateUserModel
     */
    locked: any | null;
}

/**
 * Check if a given object implements the UpdateUserModel interface.
 */
export function instanceOfUpdateUserModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authorities" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "locked" in value;

    return isInstance;
}

export function UpdateUserModelFromJSON(json: any): UpdateUserModel {
    return UpdateUserModelFromJSONTyped(json, false);
}

export function UpdateUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorities': json['authorities'],
        'email': EmailFromJSON(json['email']),
        'id': json['id'],
        'locked': json['locked'],
    };
}

export function UpdateUserModelToJSON(value?: UpdateUserModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorities': value.authorities,
        'email': EmailToJSON(value.email),
        'id': value.id,
        'locked': value.locked,
    };
}

