/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface URL
 */
export interface URL {
    /**
     * 
     * @type {any}
     * @memberof URL
     */
    value: any | null;
}

/**
 * Check if a given object implements the URL interface.
 */
export function instanceOfURL(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function URLFromJSON(json: any): URL {
    return URLFromJSONTyped(json, false);
}

export function URLFromJSONTyped(json: any, ignoreDiscriminator: boolean): URL {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function URLToJSON(value?: URL | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

